### ISSUE TITLE
./manage.py updatename not workink since Collection have been removed from snoop 2

### ISSUE THREAD

**Issue by aesraethr** [liquidinvestigations/hoover-snoop2#152]
```
Traceback (most recent call last):
  File "./manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/opt/hoover/snoop/snoop/data/management/commands/updatename.py", line 19, in handle
    collection = models.Collection.objects.get(name=collection_name)
AttributeError: module 'snoop.data.models' has no attribute 'Collection'
```

updatename should be removed or updated

**Comment by gabriel-v** [comment]
This version is outdated, see the new https://github.com/liquidinvestigations/node
